# Copyright (c) 2026, Huf and Contributors
# See license.txt

"""
Integration tests for HUF Table -> Agent access scaffolding
(huf.huf.doctype.huf_data_table.api.get_table_agent_access /
set_table_agent_access).

Creates its own fixtures (HUF Table + AI Provider/Model + Agent) because the
site has none. Class fixtures are committed explicitly: DocType creation runs
DDL (implicit commits in MariaDB), so rollback-based isolation cannot undo it.
"""

import json

import frappe
from frappe.tests import IntegrationTestCase

from huf.huf.doctype.huf_data_table.api import (
	TABLE_ACTION_MAP,
	_table_tool_name,
	create_data_table,
	delete_data_table,
	get_table_agent_access,
	set_table_agent_access,
)


class TestTableAgentAccess(IntegrationTestCase):
	TABLE_NAME = "Test Agent Access Books"
	DOCTYPE_NAME = f"HF {TABLE_NAME}"
	PROVIDER = "Test Agent Access Provider"
	MODEL = "test-agent-access-model"
	AGENT = "Test Agent Access Agent"

	@classmethod
	def setUpClass(cls):
		super().setUpClass()
		frappe.set_user("Administrator")

		result = create_data_table(
			table_name=cls.TABLE_NAME,
			fields=[
				{"label": "Title", "fieldtype": "Data"},
				{"label": "Qty", "fieldtype": "Int"},
			],
		)
		cls.registry_name = result["data"]["name"]

		frappe.get_doc(
			{
				"doctype": "AI Provider",
				"provider_name": cls.PROVIDER,
				"provider_brand": "openai",
				"api_key": "sk-test-fixture",
			}
		).insert()
		frappe.get_doc(
			{
				"doctype": "AI Model",
				"model_name": cls.MODEL,
				"provider": cls.PROVIDER,
			}
		).insert()
		frappe.get_doc(
			{
				"doctype": "Agent",
				"agent_name": cls.AGENT,
				"provider": cls.PROVIDER,
				"model": cls.MODEL,
				"instructions": "Fixture agent for table agent access tests.",
			}
		).insert()
		# DocType DDL implicitly commits in MariaDB; make fixture rows durable so
		# per-test rollback cannot remove them.
		frappe.db.commit()  # nosemgrep: test fixtures must survive DocType DDL

	@classmethod
	def tearDownClass(cls):
		frappe.set_user("Administrator")
		for doctype, name in [
			("Agent", cls.AGENT),
			("AI Model", cls.MODEL),
			("AI Provider", cls.PROVIDER),
		]:
			if frappe.db.exists(doctype, name):
				frappe.delete_doc(doctype, name, ignore_permissions=True, force=True)
		for tool in frappe.get_all(
			"Agent Tool Function",
			filters={"reference_doctype": cls.DOCTYPE_NAME},
			pluck="name",
		):
			frappe.delete_doc("Agent Tool Function", tool, ignore_permissions=True, force=True)
		if frappe.db.exists("Huf Data Table", cls.registry_name):
			delete_data_table(cls.registry_name)
		frappe.db.commit()  # nosemgrep: test fixture cleanup after DocType DDL
		super().tearDownClass()

	def tearDown(self):
		# Each test rolls back its own changes; re-assert the fixture user.
		frappe.set_user("Administrator")
		super().tearDown()

	# -- helpers -------------------------------------------------------------

	def _agent_tools(self):
		return [row.tool for row in frappe.get_doc("Agent", self.AGENT).get("agent_tool")]

	def _tool_doc(self, types):
		return frappe.get_doc("Agent Tool Function", _table_tool_name(self.DOCTYPE_NAME, types))

	# -- tests ---------------------------------------------------------------

	def test_scaffold_creates_expected_tools(self):
		result = set_table_agent_access(self.registry_name, self.AGENT, ["view", "create"])

		self.assertEqual(result["agent"], self.AGENT)
		self.assertEqual(result["actions"], ["view", "create"])

		expected = {
			"Get List": "read",
			"Get Document": "read",
			"Create Document": "create",
		}
		for types, permission in expected.items():
			doc = self._tool_doc(types)
			self.assertEqual(doc.types, types)
			self.assertEqual(doc.reference_doctype, self.DOCTYPE_NAME)
			self.assertEqual(doc.required_permission, permission)
			self.assertEqual(doc.tool_type, "Data Table")
			self.assertIn(self.TABLE_NAME, doc.description)

			# params / function_definition must be auto-generated by the
			# Agent Tool Function controller, not written by the scaffolder.
			params = json.loads(doc.params)
			self.assertEqual(params["type"], "object")
			self.assertIn("properties", params)
			definition = json.loads(doc.function_definition)
			self.assertEqual(definition["name"], doc.tool_name)
			self.assertEqual(definition["parameters"], params)

		self.assertEqual(
			sorted(self._agent_tools()),
			sorted(_table_tool_name(self.DOCTYPE_NAME, t) for t in expected),
		)

	def test_set_is_idempotent(self):
		first = set_table_agent_access(self.registry_name, self.AGENT, ["view", "edit"])

		tools_before = set(
			frappe.get_all(
				"Agent Tool Function",
				filters={"reference_doctype": self.DOCTYPE_NAME},
				pluck="name",
			)
		)

		second = set_table_agent_access(self.registry_name, self.AGENT, ["view", "edit"])
		self.assertEqual(first, second)

		tools_after = set(
			frappe.get_all(
				"Agent Tool Function",
				filters={"reference_doctype": self.DOCTYPE_NAME},
				pluck="name",
			)
		)
		self.assertEqual(tools_before, tools_after, "second call created new tool docs")

		agent_tools = self._agent_tools()
		self.assertEqual(len(agent_tools), 3)
		self.assertEqual(len(agent_tools), len(set(agent_tools)), "duplicate child rows")

	def test_uncheck_detaches_but_keeps_tool_doc(self):
		set_table_agent_access(self.registry_name, self.AGENT, ["view", "create"])
		result = set_table_agent_access(self.registry_name, self.AGENT, ["view"])

		self.assertEqual(result["actions"], ["view"])

		create_tool = _table_tool_name(self.DOCTYPE_NAME, "Create Document")
		self.assertNotIn(create_tool, self._agent_tools())
		# The tool doc must NOT be deleted — other agents may reuse it.
		self.assertTrue(frappe.db.exists("Agent Tool Function", create_tool))

		# Detaching everything leaves the agent with no access.
		empty = set_table_agent_access(self.registry_name, self.AGENT, [])
		self.assertEqual(empty["actions"], [])
		self.assertEqual(self._agent_tools(), [])

	def test_get_round_trips_set(self):
		actions = ["view", "create", "edit", "delete"]
		set_table_agent_access(self.registry_name, self.AGENT, actions)

		access = get_table_agent_access(self.registry_name)
		entry = next((e for e in access if e["agent"] == self.AGENT), None)
		self.assertIsNotNone(entry)
		self.assertEqual(entry["agent_name"], self.AGENT)
		self.assertEqual(entry["actions"], actions)
		# view -> Get List + Get Document, one tool per other action.
		self.assertEqual(len(entry["tools"]), 5)

	def test_view_counts_with_only_one_view_tool(self):
		# Hand-attach only Get List: the agent still counts as having "view",
		# and the attached tools list exposes the partial state.
		set_table_agent_access(self.registry_name, self.AGENT, [])
		agent = frappe.get_doc("Agent", self.AGENT)
		agent.append(
			"agent_tool",
			{"tool": _table_tool_name(self.DOCTYPE_NAME, "Get List")},
		)
		agent.save()

		access = get_table_agent_access(self.registry_name)
		entry = next(e for e in access if e["agent"] == self.AGENT)
		self.assertEqual(entry["actions"], ["view"])
		self.assertEqual(len(entry["tools"]), 1)

	def test_unknown_action_throws(self):
		self.assertRaises(
			frappe.ValidationError,
			set_table_agent_access,
			self.registry_name,
			self.AGENT,
			["view", "teleport"],
		)

	def test_requires_manage_capability(self):
		frappe.set_user("Guest")
		try:
			self.assertRaises(
				frappe.PermissionError,
				set_table_agent_access,
				self.registry_name,
				self.AGENT,
				["view"],
			)
			self.assertRaises(
				frappe.PermissionError,
				get_table_agent_access,
				self.registry_name,
			)
		finally:
			frappe.set_user("Administrator")

	def test_action_map_covers_four_plain_actions(self):
		self.assertEqual(set(TABLE_ACTION_MAP), {"view", "create", "edit", "delete"})
		self.assertEqual(
			[types for types, _ in TABLE_ACTION_MAP["view"]],
			["Get List", "Get Document"],
		)
