"""Subscription CLI provider adapters.

Adapters implement the SubscriptionCLIAdapter interface to communicate with
external subscription CLI providers across different transports (local, SSH, Docker).

Key architectural constraint (from plan §54.3, §69.1):
Implementations MUST NOT construct system-prompt content from HUF Agent instructions,
MUST NOT attach HUF conversation history, MUST NOT wire HUF tool schemas or an MCP
config generated by HUF, and MUST NOT invoke HUF Knowledge/Memory/Conversation Data.
This class only carries the current-turn text/files defined in SubscriptionTurnRequest's
closed field set.
"""

from __future__ import annotations

from huf.ai.subscription.adapters.base import SubscriptionCLIAdapter

__all__ = ["SubscriptionCLIAdapter"]
