"""Abstract base class for subscription CLI provider adapters.

This module defines the interface that all subscription CLI adapters must implement.
Adapters coordinate authentication, session management, and turn execution with
external CLI-based providers over different transports (local, SSH, Docker).
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from huf.ai.subscription.capabilities import RuntimeCapabilities
from huf.ai.subscription.types import AuthChallenge, AuthStatus, SubscriptionTurnRequest, SubscriptionTurnResult
from huf.ai.subscription.transports.base import ExecutionTransport

if TYPE_CHECKING:
	pass


@dataclass(frozen=True, slots=True)
class ProviderSession:
	"""Represents a session created with a subscription CLI provider.

	Attributes:
		session_id: Unique session identifier (provider-specific format)
		created_at: ISO datetime string (UTC) when the session was created
	"""

	session_id: str
	created_at: str

	def __post_init__(self) -> None:
		if not self.session_id or not self.session_id.strip():
			raise ValueError("session_id is required")
		if not self.created_at or not self.created_at.strip():
			raise ValueError("created_at (ISO datetime string) is required")


@dataclass(frozen=True, slots=True)
class SessionStatus:
	"""Status information for a provider session.

	Attributes:
		exists: True if the session exists in the provider
		detail: Optional diagnostic message about the session state
	"""

	exists: bool
	detail: str | None = None


@dataclass(frozen=True, slots=True)
class DeleteSessionResult:
	"""Result of attempting to delete a provider session.

	Attributes:
		cleanup_status: One of "deleted" (session was removed), "discarded_reference"
			(reference was discarded but provider may retain data), "provider_retained"
			(provider did not support deletion), "cleanup_failed" (deletion failed)
	"""

	cleanup_status: str

	def __post_init__(self) -> None:
		valid_statuses = {"deleted", "discarded_reference", "provider_retained", "cleanup_failed"}
		if self.cleanup_status not in valid_statuses:
			raise ValueError(
				f"cleanup_status must be one of {valid_statuses}, got {self.cleanup_status!r}"
			)


class SubscriptionCLIAdapter(ABC):
	"""Abstract base class for subscription CLI provider adapters.

	Contract and Passthrough Constraint
	====================================

	This class enforces a strict passthrough design for adapter implementations:

	IMPLEMENTATIONS MUST NOT:
	- Construct system-prompt content from HUF Agent instructions
	- Attach HUF conversation history to provider requests
	- Wire HUF tool schemas or an MCP configuration generated by HUF
	- Invoke HUF Knowledge/Memory/Conversation Data

	IMPLEMENTATIONS MAY ONLY:
	- Carry the current-turn text/files defined in SubscriptionTurnRequest's
	  closed field set (runtime_name, provider_session_id, text, files,
	  model_override, run_id, conversation_id, timeout_seconds)
	- Manage provider-specific authentication, sessions, and turn execution
	- Translate between HUF's request/response types and provider protocols

	The provider receives a bare turn with no HUF context. This is intentional:
	external CLI providers must be decoupled from HUF's agent system.

	Architecture
	============

	Adapters take an ExecutionTransport in their constructor, allowing the same
	adapter implementation to work across different execution environments (local,
	SSH, Docker). The transport abstraction manages command execution and file staging.

	Methods
	=======

	Adapters must implement:
	- probe: Verify the provider runtime is reachable and healthy
	- check_auth: Query current authentication status
	- begin_auth: Initiate an authentication flow (returns AuthChallenge)
	- submit_auth_input: Submit user input to an active challenge
	- poll_auth: Poll for challenge completion (optional, check AuthChallenge.poll_supported)
	- cancel_auth: Cancel an active challenge (default no-op, optional)
	- logout: Sign out the provider (default no-op, optional)
	- create_session: Create a new provider session
	- validate_session: Check if a session exists
	- delete_session: Remove or discard a session
	- run_turn: Execute a single turn (abstract, core method)
	"""

	def __init__(self, transport: ExecutionTransport) -> None:
		"""Initialize the adapter with an execution transport.

		Args:
			transport: ExecutionTransport instance managing command execution and file staging
		"""
		self.transport = transport

	@abstractmethod
	async def probe(self, runtime: Any) -> RuntimeCapabilities:
		"""Probe the subscription runtime and return its capabilities.

		Args:
			runtime: Loosely-typed Subscription Runtime doc/wrapper with attributes:
				- name: Runtime identifier
				- transport_type: Type of transport (local, ssh, docker)
				- executable: Path to the CLI executable
				- working_directory: Working directory for CLI execution
				- ssh_connection: SSH connection config (if transport_type == 'ssh')
				- docker_container: Container reference (if transport_type == 'docker')

		Returns:
			RuntimeCapabilities describing what the provider supports

		Raises:
			Exception: Transport-specific or probe-specific errors
		"""
		pass

	@abstractmethod
	async def check_auth(self, runtime: Any) -> AuthStatus:
		"""Check the current authentication status with the provider.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)

		Returns:
			AuthStatus describing authentication state, account hint, and method

		Raises:
			Exception: Transport-specific or auth-check errors
		"""
		pass

	@abstractmethod
	async def begin_auth(self, runtime: Any) -> AuthChallenge:
		"""Initiate an authentication flow with the provider.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)

		Returns:
			AuthChallenge describing the challenge mode and verification steps

		Raises:
			Exception: Transport-specific or auth-flow errors
		"""
		pass

	@abstractmethod
	async def submit_auth_input(self, runtime: Any, challenge_id: str, value: str) -> AuthStatus:
		"""Submit user input to an active authentication challenge.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			challenge_id: ID of the active challenge (from AuthChallenge.challenge_id)
			value: User-provided input (e.g., verification code, password, approval)

		Returns:
			AuthStatus describing the new authentication state

		Raises:
			Exception: Transport-specific or auth-submission errors
		"""
		pass

	@abstractmethod
	async def poll_auth(self, runtime: Any, challenge_id: str) -> AuthStatus:
		"""Poll for completion of an authentication challenge.

		Called when AuthChallenge.poll_supported is True and the provider supports
		polling (e.g., device-code flow, where the user approves on another device).

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			challenge_id: ID of the active challenge (from AuthChallenge.challenge_id)

		Returns:
			AuthStatus describing whether the challenge was approved/completed/failed

		Raises:
			Exception: Transport-specific or polling errors
		"""
		pass

	async def cancel_auth(self, runtime: Any, challenge_id: str) -> None:
		"""Cancel an active authentication challenge (default no-op).

		Some providers support canceling; others do not. Override if needed.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			challenge_id: ID of the active challenge (from AuthChallenge.challenge_id)

		Raises:
			Exception: Transport-specific or cancellation errors
		"""
		pass

	async def logout(self, runtime: Any) -> None:
		"""Log out / sign out the provider (default no-op).

		Some providers support explicit logout; others do not. Override if needed.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)

		Raises:
			Exception: Transport-specific or logout errors
		"""
		pass

	@abstractmethod
	async def create_session(self, request: SubscriptionTurnRequest) -> ProviderSession:
		"""Create a new session with the provider.

		Called when SubscriptionTurnRequest.provider_session_id is None,
		indicating that run_turn should establish a new session.

		Args:
			request: Subscription turn request (contains runtime_name, text, files, etc.)

		Returns:
			ProviderSession with session_id and created_at timestamp

		Raises:
			Exception: Provider-specific or session-creation errors
		"""
		pass

	@abstractmethod
	async def validate_session(self, runtime: Any, session_id: str) -> SessionStatus:
		"""Check if a session still exists and is valid.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			session_id: Session ID from a previous ProviderSession.session_id

		Returns:
			SessionStatus indicating existence and optional diagnostic message

		Raises:
			Exception: Transport-specific or validation errors
		"""
		pass

	@abstractmethod
	async def delete_session(self, runtime: Any, session_id: str) -> DeleteSessionResult:
		"""Delete or discard a session with the provider.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			session_id: Session ID from a previous ProviderSession.session_id

		Returns:
			DeleteSessionResult describing the cleanup status

		Raises:
			Exception: Transport-specific or deletion errors
		"""
		pass

	@abstractmethod
	async def run_turn(self, runtime: Any, request: SubscriptionTurnRequest) -> SubscriptionTurnResult:
		"""Execute a single turn with the provider (buffered mode).

		Core method: adapters must implement this to send a request to the provider
		and return a complete turn result. Adapters must manage session lifecycle
		(create if needed, resume if provided) based on request.provider_session_id.

		Passthrough design: adapters MUST NOT include HUF system prompts, conversation
		history, tool schemas, or knowledge context. Only the current turn's text and
		files (from SubscriptionTurnRequest) are sent to the provider.

		Args:
			runtime: Subscription Runtime doc/wrapper (see probe for attributes)
			request: Subscription turn request (text, files, model_override, etc.)

		Returns:
			SubscriptionTurnResult with status, final_text, provider_session_id,
			and optional usage, reasoning, events, debug refs

		Raises:
			Exception: Transport-specific, provider, or turn-execution errors
		"""
		pass
