# Copyright (c) 2025, Huf and contributors
# For license information, please see license.txt

"""FAISS embedded vector backend using the LlamaIndex adapter.

FAISS is an in-process, file-persisted vector index: each knowledge source
gets its own index directory under the site's private files
(``<site>/private/files/knowledge/<scrubbed_source>_faiss/``). Embeddings are
generated by HUF before chunks reach the store, per the backend contract.

Two FAISS limitations shape this backend:

* **No metadata filtering.** The LlamaIndex FAISS adapter raises on filtered
  queries, so ``supports_filters()`` is ``False`` and search relies on
  source-per-index isolation instead.
* **No deletion / no stored text.** FAISS stores only embeddings (the
  adapter's ``delete`` raises ``NotImplementedError`` and search results carry
  positional ids, not nodes). A pickled sidecar (``chunks.pkl``) maps each
  positional id to the chunk text, metadata, and embedding; scoped deletes
  drop the matching sidecar entries and rebuild the index from the surviving
  embeddings, then persist.

Salvaged from the closed PR #234 (manual persistence to Frappe private files)
and adapted to the knowledge-backend contract: HUF-side embeddings, real
``delete_chunks`` counts, ``backend_type`` in stats, an advanced-config
schema, and health/supports hooks.
"""

import os
import pickle
import uuid
from typing import Any

import frappe
from frappe import _
from frappe.utils import get_files_path

from . import ChunkResult, KnowledgeBackend
from .llamaindex_base import LLAMAINDEX_AVAILABLE, LlamaIndexBackend

try:
	import numpy as np
	from llama_index.core import Document, StorageContext
	from llama_index.core.vector_stores import VectorStoreQuery
	from llama_index.vector_stores.faiss import FaissVectorStore

	# Imported last so the llama-index-core names above stay bound (and
	# patchable in tests) when only the faiss packages are missing.
	import faiss

	FAISS_DEPS_AVAILABLE = True
except ImportError:
	FAISS_DEPS_AVAILABLE = False


# Index file name inside the persist directory. Matches the LlamaIndex
# adapter's ``from_persist_dir`` convention (``default__vector_store.json``),
# so both ``from_persist_path`` and ``from_persist_dir`` can load it.
_INDEX_FILENAME = "default__vector_store.json"
_SIDECAR_FILENAME = "chunks.pkl"

_INDEX_TYPES = {"flat", "ivf"}


class FaissBackend(LlamaIndexBackend, KnowledgeBackend):
	"""FAISS (embedded) vector backend for HUF knowledge storage.

	Best for development and small-to-medium datasets where running an
	external vector database is not warranted. The index is kept in memory
	by the LlamaIndex adapter and explicitly persisted to the site's private
	files after every mutation.

	FAISS has no native metadata filtering: ``supports_filters()`` returns
	``False`` and scoped deletion is implemented by rebuilding the index
	from the surviving chunks kept in the on-disk sidecar. For workloads
	needing filtered search or frequent deletes, use pgvector or zvec.
	"""

	_backend_type = "faiss"

	def __init__(self):
		super().__init__()
		self.persist_dir = None
		self.dimension = 1536
		self.index_type = "flat"
		self.nlist = 100
		self._index_file = None
		self._sidecar_file = None
		# Maps FAISS positional id (str) -> {"chunk_id", "text", "metadata", "embedding"}.
		self._chunk_store: dict[str, dict[str, Any]] = {}

	@classmethod
	def get_advanced_config_schema(cls) -> list[dict[str, Any]]:
		return [
			{
				"key": "faiss_index_type",
				"label": "FAISS Index Type",
				"type": "select",
				"default": "flat",
				"options": ["flat", "ivf"],
				"help_text": (
					"flat: exact brute-force L2 search (best recall, slower on large data). "
					"ivf: approximate inverted-file index (faster on large data, small recall loss). "
					"Only applies when the index is first created. Note: FAISS does not support "
					"metadata filtering; searches always cover the whole knowledge source."
				),
			},
			{
				"key": "faiss_nlist",
				"label": "IVF Clusters (nlist)",
				"type": "number",
				"default": 100,
				"min": 1,
				"max": 65536,
				"help_text": (
					"Number of Voronoi cells for the IVF index. More cells speed up search on "
					"large indexes but need enough chunks to train well. Only applies when the "
					"index is first created."
				),
				"visible_when": {"faiss_index_type": "ivf"},
			},
		]

	def _check_dependencies(self) -> None:
		if not LLAMAINDEX_AVAILABLE or not FAISS_DEPS_AVAILABLE:
			frappe.throw(
				_(
					"llama-index-vector-stores-faiss and faiss-cpu are required for faiss "
					"knowledge sources. Install them with: "
					"pip install llama-index-vector-stores-faiss faiss-cpu"
				)
			)

	def _validate_config(self) -> None:
		self.dimension = int(self.config.get("vector_dimension") or 1536)
		if self.dimension <= 0:
			frappe.throw(_("FAISS vector dimension must be positive"))

		self.index_type = (self.config.get("faiss_index_type") or "flat").lower()
		if self.index_type not in _INDEX_TYPES:
			frappe.throw(_("FAISS index type must be one of: {0}").format(", ".join(sorted(_INDEX_TYPES))))

		self.nlist = int(self.config.get("faiss_nlist") or 100)
		if self.nlist <= 0:
			frappe.throw(_("FAISS nlist must be positive"))

		files_path = get_files_path(is_private=True)
		safe_name = frappe.scrub(self.knowledge_source)
		self.persist_dir = os.path.join(files_path, "knowledge", f"{safe_name}_faiss")
		self._index_file = os.path.join(self.persist_dir, _INDEX_FILENAME)
		self._sidecar_file = os.path.join(self.persist_dir, _SIDECAR_FILENAME)

	def _before_create_vector_store(self) -> None:
		os.makedirs(self.persist_dir, exist_ok=True)

	def _create_faiss_index(self) -> Any:
		"""Build a fresh FAISS index of the configured type and dimension."""
		if self.index_type == "ivf":
			quantizer = faiss.IndexFlatL2(self.dimension)
			return faiss.IndexIVFFlat(quantizer, self.dimension, self.nlist)
		return faiss.IndexFlatL2(self.dimension)

	def _create_vector_store(self) -> Any:
		"""Load the persisted index when present, otherwise start a new one."""
		if os.path.exists(self._index_file):
			vector_store = FaissVectorStore.from_persist_path(self._index_file)
			self._validate_existing_index(vector_store)
			self._load_sidecar()
			return vector_store

		self._chunk_store = {}
		return FaissVectorStore(faiss_index=self._create_faiss_index())

	def _validate_existing_index(self, vector_store: Any) -> None:
		"""Fail loudly when a persisted index's dimension differs from the config."""
		index_dimension = int(getattr(vector_store.client, "d", 0) or 0)
		if index_dimension != self.dimension:
			frappe.throw(
				_(
					"FAISS index at '{0}' has dimension {1}, but this Knowledge Source is "
					"configured for dimension {2}. Clear the knowledge source (or remove the "
					"index directory) so it can be recreated."
				).format(self._index_file, index_dimension, self.dimension)
			)

	def _load_sidecar(self) -> None:
		self._chunk_store = {}
		if os.path.exists(self._sidecar_file):
			with open(self._sidecar_file, "rb") as sidecar:
				self._chunk_store = pickle.load(sidecar)

	def _persist(self) -> None:
		"""Write the FAISS index and the chunk sidecar to the persist directory."""
		self.vector_store.persist(persist_path=self._index_file)
		with open(self._sidecar_file, "wb") as sidecar:
			pickle.dump(self._chunk_store, sidecar)

	def _build_chunk_metadata(self, chunk: dict[str, Any], chunk_id: str) -> dict[str, Any]:
		return {
			"site_name": frappe.local.site,
			"knowledge_source": self.knowledge_source,
			"input_id": chunk["input_id"],
			"input_type": chunk["input_type"],
			"chunk_id": chunk_id,
			"source_title": chunk.get("source_title"),
			"chunk_index": chunk.get("chunk_index"),
			"char_start": chunk.get("char_start"),
			"char_end": chunk.get("char_end"),
			**(chunk.get("metadata") or {}),
		}

	def _build_search_filters(self, filters: dict[str, Any] | None) -> None:
		"""FAISS does not support metadata filtering — never build filters.

		The LlamaIndex FAISS adapter raises when a query carries filters, so
		this backend relies on source-per-index isolation instead of scoping
		filters (``site_name``/``knowledge_source`` are still recorded in the
		sidecar metadata for auditing).
		"""
		return None

	def _ensure_index_trained(self, embeddings: list[list[float]]) -> None:
		"""Train an IVF index before its first write (flat indexes are pre-trained)."""
		index = self.vector_store.client
		if getattr(index, "is_trained", True):
			return
		if len(embeddings) < self.nlist:
			frappe.logger().warning(
				f"FAISS IVF index for {self.knowledge_source} trained with "
				f"{len(embeddings)} vectors for {self.nlist} clusters; recall may be poor. "
				"Index more chunks or lower faiss_nlist."
			)
		index.train(np.array(embeddings, dtype="float32"))

	def add_chunks(self, chunks: list[dict[str, Any]]) -> int:
		"""Embed chunks via HUF, add them to the FAISS index, and persist."""
		if not chunks:
			return 0
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from huf.ai.knowledge.embedding import get_embeddings, resolve_embedding_config

		texts = [chunk["text"] for chunk in chunks]
		embed_config = resolve_embedding_config(self.knowledge_source)
		embeddings = get_embeddings(
			texts=texts,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		documents = []
		records = []
		for chunk, embedding in zip(chunks, embeddings, strict=True):
			chunk_id = chunk.get("chunk_id") or str(uuid.uuid4())
			metadata = self._build_chunk_metadata(chunk, chunk_id)
			documents.append(
				Document(
					text=chunk["text"],
					id_=chunk_id,
					embedding=embedding,
					metadata=metadata,
				)
			)
			records.append(
				{
					"chunk_id": chunk_id,
					"text": chunk["text"],
					"metadata": metadata,
					"embedding": list(embedding),
				}
			)

		self._ensure_index_trained([record["embedding"] for record in records])

		# The adapter assigns sequential positional ids (str(ntotal), ...).
		new_ids = self.vector_store.add(documents)
		for positional_id, record in zip(new_ids, records, strict=True):
			self._chunk_store[str(positional_id)] = record

		self._persist()
		return len(chunks)

	def search(
		self,
		query: str,
		top_k: int = 5,
		filters: dict[str, Any] | None = None,
	) -> list[ChunkResult]:
		"""Embed the query via HUF and run nearest-neighbor search.

		``filters`` are accepted for contract compatibility but ignored: FAISS
		cannot evaluate metadata filters. Each knowledge source has its own
		index, so results are already scoped to the source.
		"""
		if not query or not query.strip():
			return []
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		if filters:
			frappe.logger().debug(
				f"FAISS backend for {self.knowledge_source} ignores search filters "
				"(metadata filtering is not supported)."
			)

		from huf.ai.knowledge.embedding import get_embedding, resolve_embedding_config

		embed_config = resolve_embedding_config(self.knowledge_source)
		query_embedding = get_embedding(
			text=query,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		query_obj = VectorStoreQuery(
			query_embedding=query_embedding,
			similarity_top_k=top_k,
			mode="default",
		)
		result = self.vector_store.query(query_obj)

		ids = result.ids or []
		distances = result.similarities or []
		results = []
		for position, positional_id in enumerate(ids):
			record = self._chunk_store.get(str(positional_id))
			if record is None:
				continue
			# FAISS returns L2 distances; normalise to a similarity-like score.
			distance = float(distances[position]) if position < len(distances) else 0.0
			metadata = dict(record.get("metadata") or {})
			results.append(
				ChunkResult(
					chunk_id=record["chunk_id"],
					text=record["text"],
					title=metadata.get("source_title"),
					score=1.0 / (1.0 + distance),
					source=metadata.get("input_id"),
					metadata={k: v for k, v in metadata.items() if k not in self._excluded_metadata_keys},
				)
			)
		return results

	def _rebuild_index(self, keep_ids: set[str]) -> None:
		"""Recreate the index from the surviving sidecar chunks and persist.

		FAISS positional ids are reassigned in surviving order, so the sidecar
		is re-keyed to match the new index positions.
		"""
		survivors = sorted(
			(
				(int(positional_id), record)
				for positional_id, record in self._chunk_store.items()
				if positional_id in keep_ids
			),
			key=lambda entry: entry[0],
		)

		new_index = self._create_faiss_index()
		if survivors:
			embeddings = np.array([record["embedding"] for _, record in survivors], dtype="float32")
			if not getattr(new_index, "is_trained", True):
				new_index.train(embeddings)
			new_index.add(embeddings)

		self._chunk_store = {str(position): record for position, (_, record) in enumerate(survivors)}
		self.vector_store = FaissVectorStore(faiss_index=new_index)
		self.storage_context = StorageContext.from_defaults(vector_store=self.vector_store)
		self._persist()

	def delete_chunks(self, input_id: str) -> int:
		"""Delete all chunks for an input by rebuilding the index without them.

		The LlamaIndex FAISS adapter does not implement deletion, and FAISS
		positional ids shift when entries are removed, so the index is rebuilt
		from the surviving sidecar chunks and persisted. Returns the number of
		chunks removed.
		"""
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		try:
			doomed = {
				positional_id
				for positional_id, record in self._chunk_store.items()
				if (record.get("metadata") or {}).get("input_id") == input_id
			}
			if not doomed:
				return 0
			self._rebuild_index(keep_ids=set(self._chunk_store) - doomed)
			return len(doomed)
		except Exception as exc:
			frappe.logger().warning(f"FAISS delete_chunks error for {input_id}: {exc!s}")
			return 0

	def clear(self) -> None:
		"""Reset the index and sidecar to empty and persist them."""
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		self._chunk_store = {}
		self.vector_store = FaissVectorStore(faiss_index=self._create_faiss_index())
		self.storage_context = StorageContext.from_defaults(vector_store=self.vector_store)
		self._persist()

	def get_stats(self) -> dict[str, Any]:
		stats = {
			"backend_type": "faiss",
			"knowledge_source": self.knowledge_source,
			"initialized": self._initialized,
			"persist_dir": self.persist_dir,
			"vector_dimension": self.dimension,
			"index_type": self.index_type,
			"chunk_count": len(self._chunk_store),
			"size_bytes": 0,
		}

		if self.persist_dir and os.path.isdir(self.persist_dir):
			for dirpath, _dirnames, filenames in os.walk(self.persist_dir):
				stats["size_bytes"] += sum(os.path.getsize(os.path.join(dirpath, f)) for f in filenames)

		if self.vector_store is not None:
			try:
				stats["faiss_ntotal"] = int(self.vector_store.client.ntotal)
			except Exception as exc:
				frappe.logger().warning(f"FAISS get_stats ntotal error: {exc!s}")

		return stats

	def health_check(self) -> tuple[bool, str]:
		try:
			if not self._initialized:
				return (False, "Backend not initialized")
			if self.vector_store is None:
				return (False, "FAISS vector store not available")
			if not self.persist_dir or not os.path.isdir(self.persist_dir):
				return (False, f"FAISS persist directory '{self.persist_dir}' does not exist")
			return (True, "Healthy")
		except Exception as exc:
			return (False, str(exc))

	def supports_filters(self) -> bool:
		"""FAISS does not support metadata filtering."""
		return False

	def supports_hybrid_search(self) -> bool:
		"""FAISS does not support hybrid (keyword + vector) search."""
		return False
