# Copyright (c) 2025, Huf and contributors
# For license information, please see license.txt

"""Redis Vector backend implemented directly on redisvl.

This backend follows the contract's "direct implementation" path (like
``sqlite_vec``): it talks to RediSearch through redisvl's ``SearchIndex`` and
``VectorQuery`` instead of a LlamaIndex adapter, because
``llama-index-vector-stores-redis`` pins an old redisvl that is incompatible
with the bench environment. Embeddings are generated by HUF before chunks
reach the store, per the backend contract.
"""

import array
import re
import uuid
from typing import Any

import frappe
from frappe import _

from . import ChunkResult, KnowledgeBackend

try:
	import redis
	from redisvl.index import SearchIndex
	from redisvl.query import VectorQuery
	from redisvl.query.filter import Tag
	from redisvl.schema import IndexSchema

	REDIS_DEPS_AVAILABLE = True
except ImportError:
	REDIS_DEPS_AVAILABLE = False


VALID_INDEX_PREFIX = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
TAG_QUERY_SAFE = re.compile(r"([^a-zA-Z0-9_])")

# Fields returned by vector searches and mapped onto ChunkResult.
_RETURN_FIELDS = [
	"text",
	"input_id",
	"input_type",
	"chunk_id",
	"source_title",
	"chunk_index",
	"knowledge_source",
	"site_name",
]

# Metadata keys stripped from ChunkResult.metadata (mirrors LlamaIndexBackend).
_EXCLUDED_METADATA_KEYS = {"chunk_id", "source_title", "knowledge_source", "site_name"}


def _escape_tag(value: str) -> str:
	"""Escape a value for use inside a RediSearch tag query ``{...}``."""
	return TAG_QUERY_SAFE.sub(r"\\\1", value)


def _to_float32_bytes(embedding: list[float]) -> bytes:
	"""Pack an embedding into the float32 bytes RediSearch expects."""
	return array.array("f", embedding).tobytes()


class RedisBackend(KnowledgeBackend):
	"""Redis (RediSearch) vector backend for HUF knowledge storage.

	Uses redisvl's ``SearchIndex`` with an explicit ``IndexSchema`` so tag
	fields (input_id, knowledge_source, site_name, ...) are available for
	scoped filtering, deletion, and stats.
	"""

	_backend_type = "redis"

	def __init__(self):
		self.knowledge_source = None
		self.config = {}
		self.redis_client = None
		self.index = None
		self.index_name = None
		self.index_prefix = "huf"
		self.dimension = 1536
		self._initialized = False

	@classmethod
	def get_advanced_config_schema(cls) -> list[dict[str, Any]]:
		return [
			{
				"key": "redis_host",
				"label": "Redis Host",
				"type": "text",
				"default": "localhost",
				"help_text": "Hostname or IP of the Redis server.",
			},
			{
				"key": "redis_port",
				"label": "Redis Port",
				"type": "number",
				"default": 6379,
				"min": 1,
				"max": 65535,
				"help_text": "Port of the Redis server.",
			},
			{
				"key": "redis_username",
				"label": "Redis Username",
				"type": "text",
				"default": "",
				"help_text": "Optional Redis ACL username.",
			},
			{
				"key": "redis_password",
				"label": "Redis Password",
				"type": "text",
				"default": "",
				"help_text": (
					"Optional Redis password. Warning: stored in plain text inside "
					"Advanced Configuration JSON — prefer an unauthenticated local "
					"Redis or network-level access control."
				),
			},
			{
				"key": "redis_index_prefix",
				"label": "Redis Index Prefix",
				"type": "text",
				"default": "huf",
				"help_text": "Prefix used to build the RediSearch index name and keys.",
			},
		]

	def _check_dependencies(self) -> None:
		if not REDIS_DEPS_AVAILABLE:
			frappe.throw(
				_(
					"redisvl>=0.5 is required for redis knowledge sources. "
					"Install it with: pip install 'redisvl>=0.5'"
				)
			)

	def _validate_config(self) -> None:
		self.index_prefix = self.config.get("redis_index_prefix") or "huf"
		self.dimension = int(self.config.get("vector_dimension") or 1536)
		port = int(self.config.get("redis_port") or 6379)

		if not VALID_INDEX_PREFIX.match(self.index_prefix):
			frappe.throw(_("Redis index prefix must be a valid identifier"))
		if self.dimension <= 0:
			frappe.throw(_("Redis vector dimension must be positive"))
		if not 1 <= port <= 65535:
			frappe.throw(_("Redis port must be between 1 and 65535"))

	def initialize(self, knowledge_source: str, config: dict[str, Any]) -> None:
		self._check_dependencies()
		self.knowledge_source = knowledge_source
		self.config = config or {}
		self._validate_config()
		self.redis_client = self._create_redis_client()
		self.index = self._create_index()
		self._initialized = True

	def _create_redis_client(self) -> Any:
		connection_kwargs = {
			"host": self.config.get("redis_host") or "localhost",
			"port": int(self.config.get("redis_port") or 6379),
		}
		if self.config.get("redis_username"):
			connection_kwargs["username"] = self.config["redis_username"]
		if self.config.get("redis_password"):
			connection_kwargs["password"] = self.config["redis_password"]
		return redis.Redis(**connection_kwargs)

	def _create_index(self) -> Any:
		"""Build the IndexSchema and SearchIndex, creating the index if needed."""
		self.index_name = f"{self.index_prefix}_{frappe.scrub(self.knowledge_source)}"
		schema = IndexSchema.from_dict(
			{
				"index": {
					"name": self.index_name,
					"prefix": f"{self.index_name}/vector",
					"key_separator": "_",
				},
				"fields": [
					{"type": "text", "name": "text", "attrs": {"weight": 1.0}},
					{"type": "tag", "name": "input_id", "attrs": {"sortable": False}},
					{"type": "tag", "name": "input_type", "attrs": {"sortable": False}},
					{"type": "tag", "name": "chunk_id", "attrs": {"sortable": False}},
					{"type": "tag", "name": "source_title", "attrs": {"sortable": False}},
					{"type": "tag", "name": "knowledge_source", "attrs": {"sortable": False}},
					{"type": "tag", "name": "site_name", "attrs": {"sortable": False}},
					{
						"type": "vector",
						"name": "vector",
						"attrs": {
							"dims": self.dimension,
							"algorithm": "flat",
							"distance_metric": "cosine",
						},
					},
				],
			}
		)

		index = SearchIndex(schema, self.redis_client)
		try:
			index.create(overwrite=False)
		except Exception as exc:
			# An already-existing index is fine; anything else is a real problem.
			if "exists" not in str(exc).lower():
				raise
		return index

	def _chunk_to_record(
		self, chunk: dict[str, Any], chunk_id: str, embedding: list[float]
	) -> dict[str, Any]:
		return {
			"id": chunk_id,
			"text": chunk["text"],
			"vector": _to_float32_bytes(embedding),
			"site_name": frappe.local.site,
			"knowledge_source": self.knowledge_source,
			"input_id": chunk["input_id"],
			"input_type": chunk["input_type"],
			"chunk_id": chunk_id,
			"source_title": chunk.get("source_title"),
			"chunk_index": chunk.get("chunk_index"),
			**(chunk.get("metadata") or {}),
		}

	def add_chunks(self, chunks: list[dict[str, Any]]) -> int:
		if not chunks:
			return 0
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from huf.ai.knowledge.embedding import get_embeddings, resolve_embedding_config

		texts = [chunk["text"] for chunk in chunks]
		embed_config = resolve_embedding_config(self.knowledge_source)
		embeddings = get_embeddings(
			texts=texts,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		records = []
		for chunk, embedding in zip(chunks, embeddings, strict=True):
			chunk_id = chunk.get("chunk_id") or str(uuid.uuid4())
			records.append(self._chunk_to_record(chunk, chunk_id, embedding))

		if records:
			self.index.load(records)

		return len(chunks)

	def _build_filter_expression(self, filters: dict[str, Any] | None) -> Any:
		"""Build the redisvl filter expression scoping every query to this source."""
		expression = (Tag("site_name") == frappe.local.site) & (
			Tag("knowledge_source") == self.knowledge_source
		)
		if filters:
			for key, value in filters.items():
				expression &= Tag(key) == value
		return expression

	def _row_to_chunk_result(self, row: dict[str, Any]) -> ChunkResult:
		distance = row.get("vector_distance")
		score = 1.0 - float(distance) if distance is not None else 0.0
		return ChunkResult(
			chunk_id=row.get("chunk_id") or row.get("id") or "",
			text=row.get("text") or "",
			title=row.get("source_title"),
			score=score,
			source=row.get("knowledge_source"),
			metadata={
				k: v for k, v in row.items() if k not in _EXCLUDED_METADATA_KEYS and k != "vector_distance"
			},
		)

	def search(
		self,
		query: str,
		top_k: int = 5,
		filters: dict[str, Any] | None = None,
	) -> list[ChunkResult]:
		if not query or not query.strip():
			return []
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from huf.ai.knowledge.embedding import get_embedding, resolve_embedding_config

		embed_config = resolve_embedding_config(self.knowledge_source)
		query_embedding = get_embedding(
			text=query,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		vector_query = VectorQuery(
			query_embedding,
			"vector",
			num_results=top_k,
			filter_expression=self._build_filter_expression(filters),
			return_fields=list(_RETURN_FIELDS),
		)
		rows = self.index.query(vector_query)

		return [self._row_to_chunk_result(row) for row in rows]

	def delete_chunks(self, input_id: str) -> int:
		"""Delete all chunks for an input via a raw RediSearch tag query.

		Scoped by the ``site_name`` and ``knowledge_source`` tags so a shared
		Redis server never loses another source's chunks. Does not require a
		vector embedding.
		"""
		if not self._initialized or not self.redis_client:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from redis.commands.search.query import Query

		query = (
			Query(
				f"@site_name:{{{_escape_tag(frappe.local.site)}}} "
				f"@knowledge_source:{{{_escape_tag(self.knowledge_source)}}} "
				f"@input_id:{{{_escape_tag(input_id)}}}"
			)
			.paging(0, 10000)
			.no_content()
		)

		try:
			result = self.redis_client.ft(self.index_name).search(query)
			for doc in result.docs:
				self.redis_client.delete(doc.id)
			return len(result.docs)
		except Exception as exc:
			frappe.logger().warning(f"Redis delete_chunks error for {input_id}: {exc!s}")
			return 0

	def clear(self) -> None:
		"""Drop this source's RediSearch index (and its documents), then recreate it."""
		if not self._initialized or not self.index:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		try:
			self.index.delete(drop=True)
		except Exception as exc:
			frappe.logger().warning(f"Redis clear error: {exc!s}")

		# Recreate the index so it exists for subsequent operations.
		self.index = self._create_index()

	def get_stats(self) -> dict[str, Any]:
		stats = {
			"backend_type": "redis",
			"knowledge_source": self.knowledge_source,
			"initialized": self._initialized,
			"index_name": self.index_name,
			"host": self.config.get("redis_host") or "localhost",
			"port": int(self.config.get("redis_port") or 6379),
			"vector_dimension": self.dimension,
			"chunk_count": 0,
		}

		if self.redis_client and self.index_name:
			try:
				info = self.redis_client.ft(self.index_name).info()
				stats["chunk_count"] = info.get("num_docs", 0)
			except Exception as exc:
				frappe.logger().warning(f"Redis get_stats count error: {exc!s}")

		return stats

	def health_check(self) -> tuple[bool, str]:
		try:
			if not self._initialized:
				return (False, "Backend not initialized")
			if not self.redis_client:
				return (False, "Redis client not available")
			self.redis_client.ping()
			if not self.index or not self.index.exists():
				return (False, f"Redis index '{self.index_name}' does not exist")
			return (True, "Healthy")
		except Exception as exc:
			return (False, str(exc))

	def supports_filters(self) -> bool:
		"""Redis supports metadata filtering via RediSearch tag fields."""
		return True

	def supports_hybrid_search(self) -> bool:
		"""Redis hybrid search is not enabled in this backend."""
		return False
