# Copyright (c) 2025, Huf and contributors
# For license information, please see license.txt

"""Weaviate backend using the LlamaIndex adapter.

This mirrors the PGVector backend pattern: HUF resolves and generates
embeddings, while LlamaIndex owns the vector-store adapter behavior. Each
knowledge source maps to its own Weaviate collection (class) named
``Huf_<scrubbed source>`` by default; chunks additionally carry ``site_name``
and ``knowledge_source`` metadata so searches, deletes, and stats stay scoped
even when the collection name is overridden to a shared one.
"""

import re
from typing import Any

import frappe
from frappe import _

from . import ChunkResult, KnowledgeBackend
from .llamaindex_base import LLAMAINDEX_AVAILABLE, LlamaIndexBackend

try:
	import weaviate
	from llama_index.vector_stores.weaviate import WeaviateVectorStore
	from weaviate.classes.query import Filter as WeaviateFilter

	WEAVIATE_DEPS_AVAILABLE = True
except ImportError:
	WEAVIATE_DEPS_AVAILABLE = False


# Weaviate collection names must start with a capital letter and contain
# only letters, digits, and underscores.
VALID_INDEX_NAME = re.compile(r"^[A-Z][A-Za-z0-9_]*$")


class WeaviateBackend(LlamaIndexBackend, KnowledgeBackend):
	"""Weaviate vector backend for HUF knowledge storage.

	Targets a self-hosted Weaviate v4 server over HTTP + gRPC (anonymous
	access by default, optional API key). Embeddings are always generated by
	HUF; the Weaviate collection is auto-schematized from the inserted
	objects, so no server-side vectorizer is configured.
	"""

	_backend_type = "weaviate"

	def __init__(self):
		super().__init__()
		self.index_name = None
		self.http_port = 8080
		self.grpc_port = 50051
		self.client = None

	@classmethod
	def get_advanced_config_schema(cls) -> list[dict[str, Any]]:
		return [
			{
				"key": "weaviate_host",
				"label": "Weaviate Host",
				"type": "text",
				"default": "localhost",
				"help_text": "Hostname of the Weaviate server. HTTP and gRPC are assumed to share this host.",
			},
			{
				"key": "weaviate_port",
				"label": "Weaviate HTTP Port",
				"type": "number",
				"default": 8080,
				"min": 1,
				"max": 65535,
				"help_text": "HTTP/REST port of the Weaviate server.",
			},
			{
				"key": "weaviate_grpc_port",
				"label": "Weaviate gRPC Port",
				"type": "number",
				"default": 50051,
				"min": 1,
				"max": 65535,
				"help_text": "gRPC port of the Weaviate server, used for batch imports and queries.",
			},
			{
				"key": "weaviate_api_key",
				"label": "Weaviate API Key",
				"type": "text",
				"default": "",
				"help_text": (
					"API key for authenticated Weaviate servers. Leave empty for anonymous access. "
					"Warning: stored in plaintext in Advanced Configuration; prefer anonymous access "
					"on private networks."
				),
			},
			{
				"key": "weaviate_index_name",
				"label": "Collection Name Override",
				"type": "text",
				"default": "",
				"help_text": (
					"Optional Weaviate collection (class) name override. Must start with a capital "
					"letter and contain only letters, digits, and underscores. Defaults to "
					"Huf_<knowledge source name>."
				),
			},
			{
				"key": "hybrid_search",
				"label": "Hybrid Search",
				"type": "boolean",
				"default": False,
				"help_text": "Combine vector similarity with BM25 keyword matching (Weaviate hybrid search).",
			},
			{
				"key": "weaviate_hybrid_alpha",
				"label": "Hybrid Alpha",
				"type": "number",
				"default": 0.5,
				"min": 0,
				"max": 1,
				"help_text": "Balance between vector search (1.0) and keyword search (0.0) in hybrid mode.",
				"visible_when": {"hybrid_search": True},
			},
		]

	def _check_dependencies(self) -> None:
		if not LLAMAINDEX_AVAILABLE or not WEAVIATE_DEPS_AVAILABLE:
			frappe.throw(
				_(
					"llama-index-vector-stores-weaviate is required for weaviate knowledge sources. "
					"Install it with: pip install llama-index-vector-stores-weaviate"
				)
			)

	def _validate_config(self) -> None:
		self.index_name = self._resolve_index_name()
		self.http_port = self._resolve_port("weaviate_port", 8080)
		self.grpc_port = self._resolve_port("weaviate_grpc_port", 50051)

	def _resolve_port(self, key: str, default: int) -> int:
		value = self.config.get(key)
		port = int(value) if value not in (None, "") else default
		if not 1 <= port <= 65535:
			frappe.throw(_("Weaviate {0} must be between 1 and 65535").format(key))
		return port

	def _resolve_index_name(self) -> str:
		"""Resolve the Weaviate collection name for this knowledge source."""
		override = (self.config.get("weaviate_index_name") or "").strip()
		if override:
			name = override
		else:
			scrubbed = re.sub(r"[^A-Za-z0-9]", "_", self.knowledge_source or "")
			name = f"Huf_{scrubbed}"
		if not VALID_INDEX_NAME.match(name):
			frappe.throw(
				_(
					"Weaviate collection name '{0}' is invalid. It must start with a capital "
					"letter and contain only letters, digits, and underscores."
				).format(name)
			)
		return name

	def _create_weaviate_client(self) -> Any:
		host = self.config.get("weaviate_host") or "localhost"
		api_key = (self.config.get("weaviate_api_key") or "").strip()

		connect_kwargs = {
			"http_host": host,
			"http_port": self.http_port,
			"http_secure": False,
			"grpc_host": host,
			"grpc_port": self.grpc_port,
			"grpc_secure": False,
		}
		if api_key:
			connect_kwargs["auth_credentials"] = weaviate.auth.AuthApiKey(api_key)
		return weaviate.connect_to_custom(**connect_kwargs)

	def _create_vector_store(self) -> Any:
		self.client = self._create_weaviate_client()
		return WeaviateVectorStore(weaviate_client=self.client, index_name=self.index_name)

	def _build_chunk_metadata(self, chunk: dict[str, Any], chunk_id: str) -> dict[str, Any]:
		return {
			"site_name": frappe.local.site,
			"knowledge_source": self.knowledge_source,
			"input_id": chunk["input_id"],
			"input_type": chunk["input_type"],
			"chunk_id": chunk_id,
			"source_title": chunk.get("source_title"),
			"chunk_index": chunk.get("chunk_index"),
			"char_start": chunk.get("char_start"),
			"char_end": chunk.get("char_end"),
			**(chunk.get("metadata") or {}),
		}

	def _build_search_filters(self, filters: dict[str, Any] | None) -> Any:
		from llama_index.core.vector_stores.types import ExactMatchFilter, MetadataFilters

		llama_filters = [
			ExactMatchFilter(key="site_name", value=frappe.local.site),
			ExactMatchFilter(key="knowledge_source", value=self.knowledge_source),
		]
		if filters:
			llama_filters.extend(ExactMatchFilter(key=key, value=value) for key, value in filters.items())
		return MetadataFilters(filters=llama_filters)

	def _scope_filter(self, input_id: str | None = None) -> Any:
		"""Build a Weaviate where-filter scoped to site + source (+ input)."""
		where = WeaviateFilter.by_property("site_name").equal(frappe.local.site) & WeaviateFilter.by_property(
			"knowledge_source"
		).equal(self.knowledge_source)
		if input_id is not None:
			where = where & WeaviateFilter.by_property("input_id").equal(input_id)
		return where

	def _count_scoped(self, input_id: str | None = None) -> int:
		"""Count chunks for this site + knowledge source (+ optional input)."""
		if not self.client:
			return 0
		try:
			collection = self.client.collections.get(self.index_name)
			result = collection.aggregate.over_all(filters=self._scope_filter(input_id), total_count=True)
			return int(getattr(result, "total_count", 0) or 0)
		except Exception as exc:
			frappe.logger().warning(f"Weaviate count failed for {self.knowledge_source}: {exc!s}")
			return 0

	def search(
		self,
		query: str,
		top_k: int = 5,
		filters: dict[str, Any] | None = None,
	) -> list[ChunkResult]:
		"""Search chunks; uses Weaviate hybrid (vector + BM25) when enabled.

		The default path delegates to :class:`LlamaIndexBackend`, which issues a
		pure vector query. With ``hybrid_search`` enabled, the query string is
		sent alongside the embedding so Weaviate can fuse both rankings with
		``weaviate_hybrid_alpha``.
		"""
		if not self.config.get("hybrid_search"):
			return super().search(query, top_k=top_k, filters=filters)

		if not query or not query.strip():
			return []
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from llama_index.core.vector_stores import VectorStoreQuery

		from huf.ai.knowledge.embedding import get_embedding, resolve_embedding_config

		embed_config = resolve_embedding_config(self.knowledge_source)
		query_embedding = get_embedding(
			text=query,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		query_kwargs: dict[str, Any] = {
			"query_str": query,
			"query_embedding": query_embedding,
			"similarity_top_k": top_k,
			"mode": "hybrid",
			"alpha": float(self.config.get("weaviate_hybrid_alpha") or 0.5),
		}

		llama_filters = self._build_search_filters(filters)
		if llama_filters:
			query_kwargs["filters"] = llama_filters

		result = self.vector_store.query(VectorStoreQuery(**query_kwargs))

		results = []
		if result.nodes:
			for index, node in enumerate(result.nodes):
				results.append(self._node_to_chunk_result(node, result, index))
		return results

	def delete_chunks(self, input_id: str) -> int:
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from llama_index.core.vector_stores.types import ExactMatchFilter, MetadataFilters

		count_before = self._count_scoped(input_id=input_id)
		if not count_before:
			return 0
		filters = MetadataFilters(
			filters=[
				ExactMatchFilter(key="site_name", value=frappe.local.site),
				ExactMatchFilter(key="knowledge_source", value=self.knowledge_source),
				ExactMatchFilter(key="input_id", value=input_id),
			]
		)
		try:
			self.vector_store.delete_nodes(filters=filters)
		except Exception as exc:
			frappe.logger().warning(f"Weaviate delete_chunks error for {input_id}: {exc!s}")
			return 0
		return count_before

	def clear(self) -> None:
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from llama_index.core.vector_stores.types import ExactMatchFilter, MetadataFilters

		filters = MetadataFilters(
			filters=[
				ExactMatchFilter(key="site_name", value=frappe.local.site),
				ExactMatchFilter(key="knowledge_source", value=self.knowledge_source),
			]
		)
		try:
			self.vector_store.delete_nodes(filters=filters)
		except Exception as exc:
			frappe.logger().warning(f"Weaviate clear error for {self.knowledge_source}: {exc!s}")
			raise

	def get_stats(self) -> dict[str, Any]:
		return {
			"backend_type": "weaviate",
			"knowledge_source": self.knowledge_source,
			"index_name": self.index_name,
			"initialized": self._initialized,
			"chunk_count": self._count_scoped(),
			"size_bytes": 0,
		}

	def health_check(self) -> tuple[bool, str]:
		try:
			if not self._initialized:
				return (False, "Backend not initialized")
			if not self.client or not self.client.is_ready():
				return (False, "Weaviate server not ready")
			return (True, "Healthy")
		except Exception as exc:
			return (False, str(exc))

	def supports_hybrid_search(self) -> bool:
		return bool(self.config.get("hybrid_search"))
