# Copyright (c) 2025, Huf and contributors
# For license information, please see license.txt

"""Zvec embedded vector backend implemented directly on the ``zvec`` package.

This backend follows the contract's "direct implementation" path (like
``sqlite_vec`` and ``redis``): zvec is an in-process vector database (the
"SQLite of vector DBs") with no LlamaIndex adapter in the bench environment,
so the backend talks to zvec's ``Collection`` API itself. Each knowledge
source gets its own ``.zvec`` collection under the site's private files
directory. Embeddings are generated by HUF before chunks reach the store,
per the backend contract.

Salvaged from the closed PR #168 (``feature/zvec-vectorDB-integration``) and
adapted to the knowledge-backend contract: real ``delete_chunks`` counts,
``backend_type`` in stats, an advanced-config schema, injection-safe filter
building, and health/supports hooks.
"""

import json
import os
import re
import uuid
from typing import Any

import frappe
from frappe import _
from frappe.utils import get_files_path

from . import ChunkResult, KnowledgeBackend

try:
	import zvec

	ZVEC_AVAILABLE = True
except ImportError:
	ZVEC_AVAILABLE = False


# Filter field names must be plain identifiers; values are quoted separately.
VALID_FILTER_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Fields returned by vector searches and mapped onto ChunkResult.
_RETURN_FIELDS = [
	"text",
	"source_title",
	"input_id",
	"input_type",
	"chunk_index",
	"metadata_json",
]

# Scalar fields callers may filter on (all are declared in the schema).
_FILTERABLE_FIELDS = {"source_title", "input_id", "input_type", "chunk_index"}

_METRIC_TYPES = {"cosine": "COSINE", "l2": "L2", "ip": "IP"}


def _quote_filter_value(value: Any) -> str:
	"""Render a filter value as a safe zvec filter-expression literal.

	Strings are wrapped in single quotes with embedded quotes backslash-
	escaped (``o'brien`` -> ``'o\\'brien'``). zvec's filter lexer treats a
	backslash as literal except when it precedes the closing quote, so a
	string ending in a backslash cannot be represented and is rejected.
	"""
	if isinstance(value, bool):
		return "true" if value else "false"
	if isinstance(value, (int, float)):
		return repr(value)
	if not isinstance(value, str):
		frappe.throw(_("zvec filter values must be strings, numbers, or booleans"))
	if value.endswith("\\"):
		frappe.throw(_("zvec filter values may not end with a backslash"))
	return "'" + value.replace("'", "\\'") + "'"


class ZvecBackend(KnowledgeBackend):
	"""Zvec (embedded) vector backend for HUF knowledge storage.

	Stores each knowledge source as a portable ``.zvec`` collection directory
	under ``<site>/private/files/knowledge/``. Scalar fields carry the chunk
	text and metadata; filterable fields (``input_id`` etc.) get an inverted
	index so scoped filtering and deletion stay efficient.
	"""

	_backend_type = "zvec"

	# Vector field name in the zvec collection
	VECTOR_FIELD = "embedding"

	def __init__(self):
		self.knowledge_source = None
		self.config = {}
		self.collection = None
		self.db_path = None
		self.dimension = 1536
		self.metric_type = "cosine"
		self._initialized = False

	@classmethod
	def get_advanced_config_schema(cls) -> list[dict[str, Any]]:
		return [
			{
				"key": "zvec_metric_type",
				"label": "Distance Metric",
				"type": "select",
				"default": "cosine",
				"options": ["cosine", "l2", "ip"],
				"help_text": (
					"Similarity metric for the HNSW vector index. Choose based on how "
					"your embedding model was trained (cosine works for most models). "
					"Only applies when the collection is first created."
				),
			},
			{
				"key": "zvec_hnsw_m",
				"label": "HNSW M",
				"type": "number",
				"default": 16,
				"min": 2,
				"max": 100,
				"help_text": (
					"Number of bi-directional links created for each node. Higher "
					"improves recall at the cost of memory. Only applies when the "
					"collection is first created."
				),
			},
			{
				"key": "zvec_hnsw_ef_construction",
				"label": "HNSW ef_construction",
				"type": "number",
				"default": 200,
				"min": 10,
				"max": 2000,
				"help_text": (
					"Index-time candidate pool size. Higher improves index quality "
					"and recall but slows indexing. Only applies when the collection "
					"is first created."
				),
			},
			{
				"key": "zvec_hnsw_ef",
				"label": "HNSW ef (query)",
				"type": "number",
				"default": 300,
				"min": 1,
				"max": 2000,
				"help_text": (
					"Query-time candidate pool size. Higher improves recall at the cost of query latency."
				),
			},
		]

	def _check_dependencies(self) -> None:
		if not ZVEC_AVAILABLE:
			frappe.throw(
				_(
					"zvec>=0.2.1 is required for zvec knowledge sources. "
					"Install it with: pip install 'zvec>=0.2.1'"
				)
			)

	def _validate_config(self) -> None:
		self.dimension = int(self.config.get("vector_dimension") or 1536)
		if self.dimension <= 0:
			frappe.throw(_("zvec vector dimension must be positive"))

		self.metric_type = (self.config.get("zvec_metric_type") or "cosine").lower()
		if self.metric_type not in _METRIC_TYPES:
			frappe.throw(_("zvec metric type must be one of: {0}").format(", ".join(sorted(_METRIC_TYPES))))

	def initialize(self, knowledge_source: str, config: dict[str, Any]) -> None:
		"""Create or open the zvec collection for this knowledge source."""
		self._check_dependencies()
		self.knowledge_source = knowledge_source
		self.config = config or {}
		self._validate_config()

		files_path = get_files_path(is_private=True)
		knowledge_dir = os.path.join(files_path, "knowledge")
		os.makedirs(knowledge_dir, exist_ok=True)

		safe_name = frappe.scrub(knowledge_source)
		self.db_path = os.path.join(knowledge_dir, f"{safe_name}.zvec")

		if os.path.exists(self.db_path):
			self.collection = zvec.open(self.db_path)
			self._validate_existing_collection()
		else:
			self.collection = zvec.create_and_open(path=self.db_path, schema=self._build_schema())

		self._initialized = True

	def _validate_existing_collection(self) -> None:
		"""Ensure an opened collection's vector field matches this source's config.

		A collection created with a different embedding dimension cannot accept
		this source's embeddings — fail loudly at initialization instead of at
		the first insert.
		"""
		for vector_field in self.collection.schema.vectors:
			if vector_field.name == self.VECTOR_FIELD:
				if int(vector_field.dimension) != self.dimension:
					frappe.throw(
						_(
							"zvec collection at '{0}' has vector dimension {1}, but this "
							"Knowledge Source is configured for dimension {2}. Clear the "
							"knowledge source (or remove the collection directory) so it "
							"can be recreated."
						).format(self.db_path, int(vector_field.dimension), self.dimension)
					)
				return
		frappe.throw(
			_("zvec collection at '{0}' has no '{1}' vector field").format(
				self.db_path, self.VECTOR_FIELD
			)
		)

	def _build_schema(self) -> Any:
		"""Build the CollectionSchema: scalar fields + one dense vector field."""
		field_schemas = [
			zvec.FieldSchema("text", zvec.DataType.STRING, nullable=True),
			zvec.FieldSchema("source_title", zvec.DataType.STRING, nullable=True),
			zvec.FieldSchema(
				"input_id",
				zvec.DataType.STRING,
				index_param=zvec.InvertIndexParam(),
			),
			zvec.FieldSchema(
				"input_type",
				zvec.DataType.STRING,
				nullable=True,
				index_param=zvec.InvertIndexParam(),
			),
			zvec.FieldSchema("chunk_index", zvec.DataType.INT64, nullable=True),
			zvec.FieldSchema("metadata_json", zvec.DataType.STRING, nullable=True),
		]

		vector_schema = zvec.VectorSchema(
			self.VECTOR_FIELD,
			zvec.DataType.VECTOR_FP32,
			self.dimension,
			index_param=zvec.HnswIndexParam(
				metric_type=getattr(zvec.MetricType, _METRIC_TYPES[self.metric_type]),
				m=int(self.config.get("zvec_hnsw_m") or 16),
				ef_construction=int(self.config.get("zvec_hnsw_ef_construction") or 200),
			),
		)

		return zvec.CollectionSchema(
			name=frappe.scrub(self.knowledge_source),
			fields=field_schemas,
			vectors=vector_schema,
		)

	def add_chunks(self, chunks: list[dict[str, Any]]) -> int:
		"""Embed chunks via HUF and upsert them into the zvec collection."""
		if not chunks:
			return 0
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from huf.ai.knowledge.embedding import get_embeddings, resolve_embedding_config

		texts = [chunk["text"] for chunk in chunks]
		embed_config = resolve_embedding_config(self.knowledge_source)
		embeddings = get_embeddings(
			texts=texts,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		docs = []
		for chunk, embedding in zip(chunks, embeddings, strict=True):
			chunk_id = chunk.get("chunk_id") or str(uuid.uuid4())
			metadata = chunk.get("metadata") or {}
			docs.append(
				zvec.Doc(
					id=chunk_id,
					vectors={self.VECTOR_FIELD: embedding},
					fields={
						"text": chunk["text"],
						"source_title": chunk.get("source_title") or "",
						"input_id": chunk["input_id"],
						"input_type": chunk.get("input_type") or "",
						"chunk_index": chunk.get("chunk_index") or 0,
						"metadata_json": json.dumps(metadata),
					},
				)
			)

		# Upsert so re-indexing the same chunk ids stays graceful.
		result = self.collection.upsert(docs)
		statuses = result if isinstance(result, list) else [result]
		added = sum(1 for status in statuses if status.ok())
		# Persist buffered writes so stats, reopen, and crash-safety behave.
		if added:
			self.collection.flush()
		return added

	def _build_filter_expression(self, filters: dict[str, Any] | None) -> str | None:
		"""Build an injection-safe zvec filter expression from caller filters.

		Field names are validated against a strict identifier regex and the
		declared scalar fields; values are rendered through
		:func:`_quote_filter_value`, so interpolated quotes cannot break out
		of the string literal.
		"""
		if not filters:
			return None

		clauses = []
		for key, value in filters.items():
			if not VALID_FILTER_KEY.match(key) or key not in _FILTERABLE_FIELDS:
				frappe.throw(
					_("Invalid zvec filter field '{0}'. Filterable fields: {1}").format(
						key, ", ".join(sorted(_FILTERABLE_FIELDS))
					)
				)
			clauses.append(f"{key} = {_quote_filter_value(value)}")
		return " AND ".join(clauses) if clauses else None

	def _score_from_distance(self, raw_score: float) -> float:
		"""Normalise a zvec result score into a similarity-like ChunkResult score.

		zvec returns a metric-space score: for cosine it is a *distance* in
		[0, 2] (0 = identical), for L2 a distance >= 0, and for IP an inner
		product (higher = more similar).
		"""
		if self.metric_type == "cosine":
			return 1.0 - raw_score
		if self.metric_type == "l2":
			return 1.0 / (1.0 + raw_score)
		return raw_score

	def search(
		self,
		query: str,
		top_k: int = 5,
		filters: dict[str, Any] | None = None,
	) -> list[ChunkResult]:
		"""Embed the query via HUF and run approximate nearest-neighbor search."""
		if not query or not query.strip():
			return []
		if not self._initialized:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		from huf.ai.knowledge.embedding import get_embedding, resolve_embedding_config

		embed_config = resolve_embedding_config(self.knowledge_source)
		query_embedding = get_embedding(
			text=query,
			model=embed_config["model"],
			api_key=embed_config.get("api_key"),
			api_base=embed_config.get("api_base"),
		)

		vector_query = zvec.Query(
			field_name=self.VECTOR_FIELD,
			vector=query_embedding,
			param=zvec.HnswQueryParam(ef=int(self.config.get("zvec_hnsw_ef") or 300)),
		)

		query_kwargs: dict[str, Any] = {
			"queries": vector_query,
			"topk": top_k,
			"output_fields": list(_RETURN_FIELDS),
		}
		filter_expr = self._build_filter_expression(filters)
		if filter_expr:
			query_kwargs["filter"] = filter_expr

		results = self.collection.query(**query_kwargs)

		chunk_results = []
		for doc in results:
			metadata = {}
			metadata_json = doc.fields.get("metadata_json")
			if metadata_json:
				try:
					metadata = json.loads(metadata_json)
				except (json.JSONDecodeError, TypeError):
					pass

			chunk_index = doc.fields.get("chunk_index")
			if chunk_index is not None:
				metadata["chunk_index"] = chunk_index
			input_type = doc.fields.get("input_type")
			if input_type:
				metadata["input_type"] = input_type

			chunk_results.append(
				ChunkResult(
					chunk_id=doc.id,
					text=doc.fields.get("text") or "",
					title=doc.fields.get("source_title"),
					score=self._score_from_distance(float(doc.score)),
					source=doc.fields.get("input_id"),
					metadata=metadata,
				)
			)

		return chunk_results

	def delete_chunks(self, input_id: str) -> int:
		"""Delete all chunks for an input. Returns the number of chunks removed.

		``delete_by_filter`` returns ``None``, so matching docs are counted
		with a filter-only query before deleting.
		"""
		if not self._initialized or not self.collection:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		filter_expr = f"input_id = {_quote_filter_value(input_id)}"
		try:
			# Count first: a filter-only query returns matching docs in
			# storage order, capped by topk, so bound it by the doc count.
			topk = max(int(self.collection.stats["doc_count"]), 1)
			matching = list(self.collection.query(filter=filter_expr, topk=topk))
			if not matching:
				return 0
			self.collection.delete_by_filter(filter_expr)
			return len(matching)
		except Exception as exc:
			frappe.logger().warning(f"zvec delete_chunks error for {input_id}: {exc!s}")
			return 0

	def clear(self) -> None:
		"""Destroy the on-disk collection and recreate it empty."""
		if not self._initialized or not self.collection:
			raise RuntimeError("Backend not initialized. Call initialize() first.")

		self.collection.destroy()
		self.collection = zvec.create_and_open(path=self.db_path, schema=self._build_schema())

	def get_stats(self) -> dict[str, Any]:
		stats = {
			"backend_type": "zvec",
			"knowledge_source": self.knowledge_source,
			"initialized": self._initialized,
			"db_path": self.db_path,
			"vector_dimension": self.dimension,
			"metric_type": self.metric_type,
			"chunk_count": 0,
			"size_bytes": 0,
		}

		if self.db_path and os.path.exists(self.db_path):
			if os.path.isdir(self.db_path):
				for dirpath, _dirnames, filenames in os.walk(self.db_path):
					stats["size_bytes"] += sum(os.path.getsize(os.path.join(dirpath, f)) for f in filenames)
			else:
				stats["size_bytes"] = os.path.getsize(self.db_path)

		if self.collection:
			try:
				# add_chunks flushes after writing; flushing here can fail on a
				# leftover collection LOCK and must not zero out the count.
				stats["chunk_count"] = int(self.collection.stats["doc_count"])
			except Exception as exc:
				frappe.logger().warning(f"zvec get_stats count error: {exc!s}")

		return stats

	def health_check(self) -> tuple[bool, str]:
		try:
			if not self._initialized:
				return (False, "Backend not initialized")
			if not self.collection:
				return (False, "zvec collection not available")
			if not self.db_path or not os.path.exists(self.db_path):
				return (False, f"zvec collection path '{self.db_path}' does not exist")
			# Touch the collection to prove it is readable.
			int(self.collection.stats["doc_count"])
			return (True, "Healthy")
		except Exception as exc:
			return (False, str(exc))

	def supports_filters(self) -> bool:
		"""zvec supports metadata filtering via indexed scalar fields."""
		return True

	def supports_hybrid_search(self) -> bool:
		"""zvec hybrid (dense + sparse) search is not enabled in this backend."""
		return False
